### PR TITLE
Added notes in ensenso_grabber.h

### PR DESCRIPTION
**Pull request by dinhhuy2109**

### CODE REVIEW

**Comment by fsuarez6** [comment]
image

**Comment by fsuarez6** [comment]
The title of the pull request "Added notes in ensenso_grabber.h" is too generic. Please explain what you are doing here.

**Comment by dinhhuy2109** [comment]
screenshot from 2016-08-10 15 44 52

I want to merge the two branches (kinetic-devel must become the same as post-processing). But after I check out "feat/cloud-post-processing", and merge with kinetic-devel.
The post-processing become similar to kinetic-devel (not what I want).
Do you have any suggestion?

**Comment by fsuarez6** [comment]
You want to create a new branch for 7b25eaff, right?
I would checkout that commit, create the new branch and push it:

``` bash
roscd ensenso
git checkout 7b25eaff
git checkout -b <new-branch-name>
git push origin <new-branch-name>
```

Note that after the checkout, git suggest you to create the new branch.
This is how it looks my log before pushing:
image

**Comment by fsuarez6** [comment]
Assuming you will create a new branch, I'm closing this

**Comment by dinhhuy2109** [comment]
Thank you.
I did  that, and that why I have a new branch "feat/cloud-post-processing", then I continue editing a bit in this branch (the commit "added notes in .h file").
Now I want to merge the two branches before I make a pull request but then I encounter the above problem.

**Comment by fsuarez6** [comment]
Try again. I'm pretty confident you didn't do 'that'

**Comment by dinhhuy2109** [comment]
I created another one following "that".
Would you mind helping me to see what is the difference between this new branch and the one I created before.

**Comment by dinhhuy2109** [comment]
screenshot from 2016-08-10 17 10 13

**Comment by dinhhuy2109** [comment]
Actually, you need to `cherry-pick` 7b25eaf: http://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean

**Pull request closed without merging**
